# Generated by Django 4.2.6 on 2023-10-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_lyst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lyst',
            new_name='Liste',
        ),
    ]
